export default (interest) => {
  const categories = [
    { id: '1334134',
      status: false,
      name: 'Arts, Crafts & Sewing' },
    { id: '91083',
      status: false,
      name: 'Auto & Tires' },
    { id: '5427',
      status: false,
      name: 'Baby' },
    { id: '1085666',
      status: false,
      name: 'Beauty' },
    { id: '3920',
      status: false,
      name: 'Books' },
    { id: '1105910',
      status: false,
      name: 'Cell Phones' },
    { id: '5438',
      status: false,
      name: 'Clothing' },
    { id: '3944',
      status: false,
      name: 'Electronics' },
    { id: '976759',
      status: false,
      name: 'Food' },
    { id: '1094765',
      status: false,
      name: 'Gifts & Registry' },
    { id: '976760',
      status: false,
      name: 'Health' },
    { id: '4044',
      status: false,
      name: 'Home' },
    { id: '1072864',
      status: false,
      name: 'Home Improvement' },
    { id: '1115193',
      status: false,
      name: 'Household Essentials' },
    { id: '6197502',
      status: false,
      name: 'Industrial & Scientific' },
    { id: '3891',
      status: false,
      name: 'Jewelry' },
    { id: '4096',
      status: false,
      name: 'Movies & TV' },
    { id: '4104',
      status: false,
      name: 'Music on CD or Vinyl' },
    { id: '7796869',
      status: false,
      name: 'Musical Instruments' },
    { id: '1229749',
      status: false,
      name: 'Office' },
    { id: '2637',
      status: false,
      name: 'Party & Occasions' },
    { id: '5428',
      status: false,
      name: 'Patio & Garden' },
    { id: '1005862',
      status: false,
      name: 'Personal Care' },
    { id: '5440',
      status: false,
      name: 'Pets' },
    { id: '5426',
      status: false,
      name: 'Photo Center' },
    { id: '1085632',
      status: false,
      name: 'Seasonal' },
    { id: '6163033',
      status: false,
      name: 'Services' },
    { id: '4125',
      status: false,
      name: 'Sports & Outdoors' },
    { id: '4171',
      status: false,
      name: 'Toys' },
    { id: '2636',
      status: false,
      name: 'Video Games' },
  ]
  for (category of categories) {
    if(interest === category.name) {
      return category.id;
    }
  }

  return -1;
}
